import Head from 'next/head'
import Image from 'next/image'
import tw from 'twin.macro'
import { Swiper, SwiperSlide } from 'swiper/react'
import 'swiper/css'
import 'swiper/css/navigation'
import 'swiper/css/pagination'
import { Pagination, Navigation, Scrollbar, Autoplay } from "swiper"
import { HiBars3, HiMagnifyingGlass, HiOutlineBell, HiChevronRight, HiChevronLeft, HiXMark, HiLockClosed, HiOutlineHeart, HiOutlineUser } from 'react-icons/hi2'
import Button from '../../components/core/button/Button'
import Avatar from '../../components/core/avatar/Avatar'
import MainCarousel from '../../components/overlay/mainCarosel/MainCarosel'
import { useEffect, useRef, useState } from 'react'
import useDetectClose from '../../components/hooks/useDetectClose'

export default function Detail() {


  const prevRef = useRef(null);
  const nextRef = useRef(null);
  const pageRef= useRef(null);

  const [myPageIsOpen, myPageRef, myPageHandler] = useDetectClose(false);
  const [sidebarIsOpen, sidebarRef, sidebarHandler] = useDetectClose(false);
  
  return (
    <>
      <Head>
        <title>쿠키블</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header tw="w-full h-16 border-b border-gray-200">
        <nav tw="relative flex justify-between items-center max-w-screen-lg mx-auto px-4 py-2">
          <div tw="lg:hidden">
            <button
              ref={sidebarRef}
              type="button"
              tw="p-3 hover:bg-gray-50 active:bg-gray-100 rounded-full"
              onClick={sidebarHandler}
            >
              <HiBars3 tw="w-6 h-6 text-gray-400"/>
            </button>
          </div>
          <div tw="flex justify-between items-center space-x-4">
            <div tw="inline-flex font-jua">
              <span tw="text-2xl font-bold">C</span>
              <span tw="text-2xl font-bold text-[#E7CE96]">OO</span>
              <span tw="text-2xl font-bold">KVEL</span>
            </div>

            <div tw="hidden lg:flex space-x-4 text-base">
              <a tw="px-4 py-2 font-semibold hover:(underline decoration-4 underline-offset-4 decoration-[#E7CE96]) rounded-lg" href="">자유연재</a>
              <a tw="px-4 py-2 font-semibold hover:(underline decoration-4 underline-offset-4 decoration-[#E7CE96]) rounded-lg" href="">리뷰</a>
              <a tw="px-4 py-2 font-semibold hover:(underline decoration-4 underline-offset-4 decoration-[#E7CE96]) rounded-lg" href="">내 서재</a>
            </div>
          </div>

          <div tw="flex justify-between items-center">
            <button
              type="button"
              tw="p-3 hover:bg-gray-50 active:bg-gray-100 rounded-full"
            >
              <HiMagnifyingGlass tw="w-6 h-6 text-gray-400"/>
            </button>
            <button
               type="button"
               tw="hidden lg:block p-3 hover:bg-gray-50 active:bg-gray-100 rounded-full"
              >
              <HiOutlineBell tw="w-6 h-6 text-gray-400"/>
            </button>
            <div tw="hidden">

            </div>              
              {
                 
              <>
              {                
              <button tw="hidden md:flex items-center ml-3" type="button" ref={myPageRef} onClick={myPageHandler}>
                <Avatar size="sm" alt="avatar" src={"https://api.lorem.space/image/face?w=128&h=128&hash=BDC01094"} width={32} height={32}/>
              </button>
              }
              <div css={[tw`hidden absolute bg-white w-[100px] h-full rounded-lg top-10 right-0 z-10 mt-4 origin-top-right shadow duration-150 ease-in-out`, myPageIsOpen ? tw`opacity-100`: tw`opacity-0`]}>
                <ul tw="text-center">
                  <li>메뉴</li>
                  <li>메뉴</li>
                </ul>
              </div>
              </>
              }
          </div>
        </nav>
      </header>
      <div tw="md:hidden border-b border-gray-200">
        <nav tw="relative flex justify-between items-center text-center max-w-screen-lg mx-auto">
          <a tw="py-3 w-full font-semibold active:bg-gray-100" href="">자유연재</a>
          <a tw="py-3 w-full font-semibold">리뷰</a>
          <a tw="py-3 w-full font-semibold">내 서재</a>
        </nav>
      </div>
      <aside tw="absolute w-[300px] md:hidden h-screen bg-gray-50 top-0 z-50 duration-300 transition-all ease-in-out shadow" css={[sidebarIsOpen ? tw``: tw`-translate-x-[300px]`]}>
        <nav tw="">
          <div tw="flex justify-end border-b border-gray-400 p-3">
            <button type="button" onClick={sidebarHandler}><HiXMark tw="w-8 h-8"/></button>
          </div>
          <div tw="flex items-center p-3">
            <Avatar size="md" alt="avatar" src={"https://api.lorem.space/image/face?w=128&h=128&hash=BDC01094"} width={48} height={48}/>
            <div tw="ml-4">
              <p tw="text-xl font-bold">빵냥 님</p>
              <span tw="text-gray-400">mkht0210@gmail.com</span>
            </div>
          </div>
          <div tw="flex flex-col p-3">
            <a tw="px-4 py-2 w-full hover:bg-gray-100 font-semibold text-lg">알림</a>
            <a tw="px-4 py-2 w-full hover:bg-gray-100 font-semibold text-lg">내 서재</a>
            <a tw="px-4 py-2 w-full hover:bg-gray-100 font-semibold text-lg">작품 쓰기</a>
            <a tw="px-4 py-2 w-full hover:bg-gray-100 font-semibold text-lg">스토리룸</a>
            <a tw="px-4 py-2 w-full hover:bg-gray-100 font-semibold text-lg">이벤트</a>
            <a tw="px-4 py-2 w-full hover:bg-gray-100 font-semibold text-lg">고객센터</a>
            <a tw="px-4 py-2 w-full hover:bg-gray-100 font-semibold text-lg">공지사항</a>
          </div>
        </nav>
      </aside>
      <main tw="flex flex-col mt-[50px]">
        <secton tw="max-w-screen-lg mx-auto">
          <div tw="flex flex-col">
          <div tw="w-full flex gap-6 py-6">
            <div tw="">
              <a tw="relative block w-48 h-64 rounded-lg overflow-hidden">
                <img tw="w-full h-full" src="https://api.lorem.space/image/movie?w=208&h=240" alt="책표지" />
              </a>
            </div>
            <div tw="flex flex-col gap-4">
              <div tw="flex justify-between">
                <div tw="">
                  <h1 tw="text-3xl font-bold">제목입니다</h1>
                  <span tw="">닉네임</span>
                  <span tw="ml-2 text-gray-400">300화</span>
                </div>
                <div tw="ml-2 md:inline-flex gap-6 text-gray-400 hidden">
                  <div tw="flex flex-col items-center">
                    <HiOutlineUser tw="w-6 h-6 stroke-1 stroke-gray-400 fill-white"/>
                    <span tw="text-sm">13</span>
                  </div>
                  <div tw="flex flex-col items-center">
                    <HiOutlineHeart tw="w-6 h-6 stroke-1 stroke-gray-400 fill-white"/>
                    <span tw="text-sm">13</span>
                    </div>
                  <div tw="flex flex-col items-center">
                    <HiOutlineBell tw="w-6 h-6 stroke-1 text-gray-400"/>
                    <span tw="text-sm">12</span>
                  </div>
                </div> 
              </div>
              <article tw="">
              들어 같은 풀밭에 그들은 그것은 끓는다, 천하를 싸인 원질이 이상 있으며. 속잎나고. 설레는 찾아 방황하였으며. 위하여 작고 우리의 것이다, 인간에 고행을 있다, 그것을 창공에 영원히 있는가? 품었기 힘차게 예가 봄바람이다. 위하여서 물방아 되는 귀는 그들은 현저하게 것이다.

못하다 피어나기 천하를 구할 그것을 그들의 것이다. 
              </article>
              <div tw="flex flex-wrap gap-2">
                  <a tw="bg-gray-100 rounded px-2 py-0.5 hover:bg-gray-200 cursor-pointer">
                    <span tw="text-sm text-gray-400">태그</span>
                  </a>
                  <a tw="bg-gray-100 rounded px-2 py-0.5 hover:bg-gray-200">
                    <span tw="text-sm text-gray-400">태그</span>
                  </a>
                  <a tw="bg-gray-100 rounded px-2 py-0.5">
                    <span tw="text-sm text-gray-400">태그</span>
                  </a>
                  <a tw="bg-gray-100 rounded px-2 py-0.5">
                    <span tw="text-sm text-gray-400">태그</span>
                  </a>
                  <a tw="bg-gray-100 rounded px-2 py-0.5">
                    <span tw="text-sm text-gray-400">태그</span>
                  </a>
                  <a tw="bg-gray-100 rounded px-2 py-0.5">
                    <span tw="text-sm text-gray-400">태그</span>
                  </a>
              </div>
              <div tw="flex justify-center gap-4">
                <button tw="w-full bg-black text-white py-2 text-center border border-black rounded-lg">첫 화 보기</button>
                <button tw="w-full bg-white text-black py-2 text-center border border-black rounded-lg">구독하기</button>
              </div>
            </div>
          </div>
          <div tw="w-full border-b border-gray-200"></div>
          <div tw="flex justify-between gap-6">

            <div tw="w-full py-6">
              <div tw="w-full flex justify-between items-center border-b border-gray-200 py-2">
                <div tw="flex gap-4">
                  <div tw="text-sm">최신순</div>
                  <div tw="text-sm">연재순</div>
                  <div tw="text-sm">보던순</div>
                </div>
                <div tw="text-sm">
                  총 300화
                </div>
              </div>
              <div tw="flex gap-6 py-4 h-40">
                <div tw="">
                  <a tw="block relative w-24 h-32 rounded-lg overflow-hidden">
                    <img tw="w-full h-full object-cover" src="https://api.lorem.space/image/movie?w=160&h=200" alt="책표지"/>
                  </a>
                </div>
                <div tw="h-36 flex flex-1 flex-col items-stretch">
                  <div tw="">
                    <h1 tw="text-base font-semibold">제목입니다</h1>
                    <span tw="text-sm text-gray-400">20화</span>
                  </div>
                  <div tw="text-sm text-gray-400 line-clamp-1">
                    한줄 설명입니다
                  </div>
                  <div tw="md:inline-flex gap-4 text-gray-400 hidden items-end">
                  <div tw="flex items-center">
                    <HiOutlineUser tw="w-4 h-4 stroke-1 stroke-gray-400 fill-white"/>
                    <span tw="text-sm">13</span>
                  </div>
                  <div tw="flex items-center">
                    <HiOutlineHeart tw="w-4 h-4 stroke-1 stroke-gray-400 fill-white"/>
                    <span tw="text-sm">13</span>
                    </div>
                  </div>
                </div>
                <div tw="flex items-center justify-end">
                  <button tw="p-3 hover:bg-gray-200 active:bg-gray-300 rounded-full" type="button">
                    <HiLockClosed tw="w-6 h-6 fill-gray-400" />
                  </button>
                </div>
              </div>
              <div tw="flex gap-6 py-4 h-40">
                <div tw="">
                  <a tw="block relative w-24 h-32 rounded-lg overflow-hidden">
                    <img tw="w-full h-full object-cover" src="https://api.lorem.space/image/movie?w=160&h=200" alt="책표지"/>
                  </a>
                </div>
                <div tw="h-36 flex flex-1 flex-col items-stretch">
                  <div tw="">
                    <h1 tw="text-base font-semibold">제목입니다</h1>
                    <span tw="text-sm text-gray-400">20화</span>
                  </div>
                  <div tw="text-sm text-gray-400 line-clamp-1">
                    한줄 설명입니다
                  </div>
                  <div tw="md:inline-flex gap-4 text-gray-400 hidden items-end">
                  <div tw="flex items-center">
                    <HiOutlineUser tw="w-4 h-4 stroke-1 stroke-gray-400 fill-white"/>
                    <span tw="text-sm">13</span>
                  </div>
                  <div tw="flex items-center">
                    <HiOutlineHeart tw="w-4 h-4 stroke-1 stroke-gray-400 fill-white"/>
                    <span tw="text-sm">13</span>
                    </div>
                  </div>
                </div>
                <div tw="flex items-center justify-end">
                  <button tw="p-3 hover:bg-gray-200 active:bg-gray-300 rounded-full" type="button">
                    <HiLockClosed tw="w-6 h-6 fill-gray-400" />
                  </button>
                </div>
              </div>
              <div tw="bg-gray-200 border-b w-full"></div>
              <div tw="flex gap-6 py-4 h-40">
                <div tw="">
                  <a tw="block relative w-24 h-32 rounded-lg overflow-hidden">
                    <img tw="w-full h-full object-cover" src="https://api.lorem.space/image/movie?w=160&h=200" alt="책표지"/>
                  </a>
                </div>
                <div tw="h-36 flex flex-1 flex-col items-stretch">
                  <div tw="">
                    <h1 tw="text-base font-semibold">제목입니다</h1>
                    <span tw="text-sm text-gray-400">20화</span>
                  </div>
                  <div tw="text-sm text-gray-400 line-clamp-1">
                    한줄 설명입니다
                  </div>
                  <div tw="md:inline-flex gap-4 text-gray-400 hidden items-end">
                  <div tw="flex items-center">
                    <HiOutlineUser tw="w-4 h-4 stroke-1 stroke-gray-400 fill-white"/>
                    <span tw="text-sm">13</span>
                  </div>
                  <div tw="flex items-center">
                    <HiOutlineHeart tw="w-4 h-4 stroke-1 stroke-gray-400 fill-white"/>
                    <span tw="text-sm">13</span>
                    </div>
                  </div>
                </div>
                <div tw="flex items-center justify-end">
                  <button tw="p-3 hover:bg-gray-200 active:bg-gray-300 rounded-full" type="button">
                    <HiLockClosed tw="w-6 h-6 fill-gray-400" />
                  </button>
                </div>
              </div>
              <div tw="bg-gray-200 border-b w-full"></div>
              <div tw="flex justify-center">
                <div tw="py-6 flex gap-4">
                  <button tw="p-3 hover:bg-gray-200 active:bg-gray-300 rounded-full" type="button">
                    <HiChevronLeft tw="w-6 h-6 text-gray-400" />
                  </button>
                  <button tw="p-3 hover:bg-gray-200 active:bg-gray-300 rounded-full" type="button">
                    <div tw="w-6 h-6">1</div>
                  </button>
                  <button tw="p-3 hover:bg-gray-200 active:bg-gray-300 rounded-full" type="button">
                    <div tw="w-6 h-6">2</div>
                  </button>
                  <button tw="p-3 hover:bg-gray-200 active:bg-gray-300 rounded-full" type="button">
                    <div tw="w-6 h-6">3</div>
                  </button>
                  <button tw="p-3 hover:bg-gray-200 active:bg-gray-300 rounded-full" type="button">
                    <div tw="w-6 h-6">4</div>
                  </button>
                  <button tw="p-3 hover:bg-gray-200 active:bg-gray-300 rounded-full" type="button">
                    <div tw="w-6 h-6">5</div>
                  </button>
                  <button tw="p-3 hover:bg-gray-200 active:bg-gray-300 rounded-full" type="button">
                    <div tw="w-6 h-6">6</div>
                  </button>
                  <button tw="p-3 hover:bg-gray-200 active:bg-gray-300 rounded-full" type="button">
                    <HiChevronRight tw="w-6 h-6 text-gray-400" />
                  </button>
                </div>
              </div>
            </div>
            <div tw="py-6 w-96 mx-auto">
              <div tw="flex flex-col items-center px-6 py-6 bg-gray-100 rounded-lg">
                <a tw="block relative w-36 h-36 rounded-lg overflow-hidden">
                  <img tw="w-full h-full object-cover" src="https://api.lorem.space/image/face?w=200&h=200" alt="닉네임"/>
                </a>
                <div tw="py-4">
                  <h3 tw="text-base font-bold">닉네임</h3>
                  <p tw="text-gray-400">소개말입니다.</p>
                  <span tw="text-sm">대표작이름, 대표작이름</span>
                </div>
                <div tw="">
                  <button type="button" tw="w-full bg-black px-6 py-3 text-white rounded-lg">작가 팔로우하기</button>
                </div>
              </div>
              <div tw="flex gap-4 px-6 py-6 bg-gray-100 rounded-lg my-6">
                <a tw="block relative w-24 h-32 rounded-lg overflow-hidden">
                  <img tw="w-full h-full object-cover" src="https://api.lorem.space/image/movie?w=160&h=200" alt="닉네임"/>
                </a>
                <div tw="">
                  <h3 tw="text-base font-bold">작품명입니다</h3>
                  <span tw="text-sm">30화 | 연재중</span>
                  <p tw="text-gray-400">소개말입니다.</p>
                  
                </div>
              </div>
              <div tw="flex gap-4 px-6 py-6 bg-gray-100 rounded-lg">
                <a tw="block relative w-24 h-32 rounded-lg overflow-hidden">
                  <img tw="w-full h-full object-cover" src="https://api.lorem.space/image/movie?w=160&h=200" alt="닉네임"/>
                </a>
                <div tw="">
                  <h3 tw="text-base font-bold">작품명입니다</h3>
                  <span tw="text-sm">30화 | 연재중</span>
                  <p tw="text-gray-400">소개말입니다.</p>
                  
                </div>
              </div>
            </div>
          </div>
          </div>
        </secton>             
      </main>
      <footer>
        
      </footer>
    </>
  )
}

