import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import tw from 'twin.macro'
import { Swiper, SwiperSlide } from 'swiper/react'
import 'swiper/css'
import 'swiper/css/navigation'
import 'swiper/css/pagination'
import { Pagination, Navigation, Scrollbar, Autoplay } from "swiper"
import { HiFilter } from 'react-icons/hi'
import { HiBars3, HiMagnifyingGlass, HiOutlineBell, HiChevronRight, HiChevronLeft, HiXMark, HiAdjustmentsHorizontal, HiChevronDown, HiOutlineChevronDown, HiOutlineChevronUp, HiEye, HiHeart, HiBookmark, HiUser, HiOutlineChevronLeft, HiOutlineChevronRight } from 'react-icons/hi2'
import Button from '../../components/core/button/Button'
import Avatar from '../../components/core/avatar/Avatar'
import MainCarousel from '../../components/overlay/mainCarosel/MainCarosel'
import { useEffect, useRef, useState } from 'react'
import useDetectClose from '../../components/hooks/useDetectClose'
import { faker } from '@faker-js/faker'
import BookItem from './bookItem'

export default function Nextpage() {

  const handleAvatar = async () => {
    const res = await fetch("https://i.pravatar.cc/48");

    return res.json();
  }

  const src= "https://i.pravatar.cc/48/"

  const [dropdownIsOpen, dropdownRef,dropdownHandler] = useDetectClose(false); 

  const [myPageIsOpen, myPageRef, myPageHandler] = useDetectClose(false);
  const [sidebarIsOpen, sidebarRef, sidebarHandler] = useDetectClose(false);
  return (
    <>
      <Head>
        <title>쿠키블</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header tw="w-full h-16 border-b border-gray-200">
        <nav tw="relative flex justify-between items-center max-w-screen-lg mx-auto px-4 py-2">
          <div tw="lg:hidden">
            <button
              ref={sidebarRef}
              type="button"
              tw="p-3 hover:bg-gray-50 active:bg-gray-100 rounded-full"
              onClick={sidebarHandler}
            >
              <HiBars3 tw="w-6 h-6 text-gray-400"/>
            </button>
          </div>
          <div tw="flex justify-between items-center space-x-4">
            <div tw="inline-flex mb-1">
              <span tw="text-2xl font-bold">C</span>
              <span tw="text-2xl font-bold text-[#E7CE96]">OO</span>
              <span tw="text-2xl font-bold">KVEL</span>
            </div>

            <div tw="hidden lg:flex space-x-4 text-base">
              <a tw="px-4 py-2 font-semibold hover:(underline decoration-4 underline-offset-4 decoration-[#E7CE96]) rounded-lg" href="">자유연재</a>
              <a tw="px-4 py-2 font-semibold hover:(underline decoration-4 underline-offset-4 decoration-[#E7CE96]) rounded-lg" href="">리뷰</a>
              <a tw="px-4 py-2 font-semibold hover:(underline decoration-4 underline-offset-4 decoration-[#E7CE96]) rounded-lg" href="">내 서재</a>
            </div>
          </div>

          <div tw="flex justify-between items-center">
            <button
              type="button"
              tw="p-3 hover:bg-gray-50 active:bg-gray-100 rounded-full"
            >
              <HiMagnifyingGlass tw="w-6 h-6 text-gray-400"/>
            </button>
            <button
               type="button"
               tw="hidden lg:block p-3 hover:bg-gray-50 active:bg-gray-100 rounded-full"
              >
              <HiOutlineBell tw="w-6 h-6 text-gray-400"/>
            </button>
            <div tw="hidden">

            </div>              
              {
                 
              <>
              <button tw="hidden md:block ml-3" type="button" ref={myPageRef} onClick={myPageHandler}>
                  <Avatar size="sm" alt="avatar" src={"https://api.lorem.space/image/face?w=128&h=128&hash=BDC01094"} width={32} height={32}/>
              </button>
              <div css={[tw`hidden absolute bg-white w-[100px] h-full rounded-lg top-10 right-0 z-10 mt-4 origin-top-right shadow duration-150 ease-in-out`, myPageIsOpen ? tw`opacity-100`: tw`opacity-0`]}>
                <ul tw="text-center">
                  <li>메뉴</li>
                  <li>메뉴</li>
                </ul>
              </div>
              </>
              }
          </div>
        </nav>
      </header>
      <div tw="md:hidden border-b border-gray-200">
        <nav tw="relative flex justify-between items-center text-center max-w-screen-lg mx-auto">
          <a tw="py-3 w-full font-semibold active:bg-gray-100" href="">자유연재</a>
          <a tw="py-3 w-full font-semibold">리뷰</a>
          <a tw="py-3 w-full font-semibold">내 서재</a>
        </nav>
      </div>
      <aside tw="absolute w-[300px] md:hidden h-screen bg-gray-50 top-0 z-50 duration-300 transition-all ease-in-out shadow" css={[sidebarIsOpen ? tw``: tw`-translate-x-[300px]`]}>
        <nav tw="">
          <div tw="flex justify-end border-b border-gray-400 p-3">
            <button type="button" onClick={sidebarHandler}><HiXMark tw="w-8 h-8"/></button>
          </div>
          <div tw="flex items-center p-3">
            <Avatar size="md" alt="avatar" src={"https://api.lorem.space/image/face?w=128&h=128&hash=BDC01094"} width={48} height={48}/>
            <div tw="ml-4">
              <p tw="text-xl font-bold">빵냥 님</p>
              <span tw="text-gray-400">mkht0210@gmail.com</span>
            </div>
          </div>
          <div tw="flex flex-col p-3">
            <a tw="px-4 py-2 w-full hover:bg-gray-100 font-semibold text-lg">알림</a>
            <a tw="px-4 py-2 w-full hover:bg-gray-100 font-semibold text-lg">내 서재</a>
            <a tw="px-4 py-2 w-full hover:bg-gray-100 font-semibold text-lg">작품 쓰기</a>
            <a tw="px-4 py-2 w-full hover:bg-gray-100 font-semibold text-lg">스토리룸</a>
            <a tw="px-4 py-2 w-full hover:bg-gray-100 font-semibold text-lg">이벤트</a>
            <a tw="px-4 py-2 w-full hover:bg-gray-100 font-semibold text-lg">고객센터</a>
            <a tw="px-4 py-2 w-full hover:bg-gray-100 font-semibold text-lg">공지사항</a>
          </div>
        </nav>
      </aside>
      <main tw="w-full flex flex-col mt-[115px] overflow-x-hidden">
             
        <section tw="relative w-full max-w-screen-lg mx-auto">
          <header>
            <nav tw="">

            </nav>
          </header>
          <div tw="max-w-screen-lg w-full flex items-center justify-between h-12 border-b mx-auto px-2">
            <button
              ref={dropdownRef}
              tw="flex items-center"
              type="button"
              onClick={dropdownHandler}
            >
              <span tw="mr-2">최신순</span>
              {dropdownIsOpen ? <HiOutlineChevronDown tw="w-4 h-4"/> : <HiOutlineChevronUp tw="w-4 h-4"/>}
            </button>
            <button
              tw="flex items-center" 
              type="button">
                <HiAdjustmentsHorizontal tw="w-8 h-8"/>
                <span tw="ml-2">필터</span>
            </button>
          </div>
          {dropdownIsOpen &&
            <div tw="absolute bg-gray-50 w-20 h-20 border rounded-lg z-10">
              <div>최신순</div>
              <div>인기순</div>
            </div>}
        </section>
        <section tw="mt-12 max-w-screen-lg mx-auto">
          <div tw="flex flex-wrap mx-auto mb-4">
            <div tw="w-full border-b border-gray-200"></div>
              <BookItem/>
            <div tw="w-full border-b border-gray-200"></div>
            <BookItem/>
            <div tw="w-full border-b border-gray-200"></div>
            <BookItem/>
            <div tw="w-full border-b border-gray-200"></div>
          </div>
          <div tw="">
            <div tw="flex justify-center items-center gap-6">
              <a tw="px-3 py-1.5"><HiOutlineChevronLeft tw="w-6 h-6"/></a>
              <a tw="px-3 py-1.5 bg-black text-white rounded-lg">1</a>
              <a tw="px-3 py-1.5 ">2</a>
              <a tw="px-3 py-1.5 ">3</a>
              <a tw="px-3 py-1.5 ">4</a>
              <a tw="px-3 py-1.5 ">5</a>
              <a tw="px-3 py-1.5"><HiOutlineChevronRight tw="w-6 h-6"/></a>
            </div>
          </div>
        </section>

      </main>
      <footer>
        
      </footer>
    </>
  )
}

