import Head from "next/head"
import tw from 'twin.macro'
import {faker} from '@faker-js/faker'
import Image from "next/image"
import { HiOutlineArrowLeft, HiOutlineChevronLeft, HiOutlineChevronRight, HiOutlineEye, HiOutlinePencilSquare, HiOutlineTrash } from 'react-icons/hi2'
import Link from "next/link"
import { router } from "next/router"

const ChapterList = () => {

  const imgUrl = faker.image.animals(300,400);
  return (
    <>
      <Head>
        <title>쿠키블</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header tw="w-full border-b border-gray-200">
        <nav tw="flex justify-start items-center max-w-screen-lg mx-auto py-2">
          <div tw="relative">
            <button tw="p-3">
              <HiOutlineArrowLeft tw="w-6 h-6 stroke-gray-400" />
            </button>
          </div>
          <div tw="flex items-center text-xl font-bold">회차 목록</div>
        </nav>
      </header>
      <nav tw="max-w-screen-lg mx-auto my-4">
        <div tw="flex justify-between divide-x border rounded-lg border-gray-200 mx-4">
          <Link tw="w-1/3 text-center py-3 hover:bg-gray-100" href="/storyroom/chapters/chapterList">회차 목록</Link>
          <Link tw="w-1/3 text-center py-3 hover:bg-gray-100" href="/storyroom/chapters/noticeList">공지 목록</Link>
          <Link tw="w-1/3 text-center py-3 hover:bg-gray-100" href="">일별 통계</Link>
        </div> 
      </nav>
      <main tw="max-w-screen-lg mx-auto">
        <div tw="flex lg:flex-row flex-col gap-12 px-4">
          <div tw="flex flex-col border rounded px-4 py-3 my-3">
            <div tw="flex justify-center items-center rounded-lg overflow-hidden mb-4">
              <Image src={imgUrl} alt="random test image" width={300} height={400}/>
            </div>
            <div tw="flex flex-col">
              <h1 tw="text-2xl">제목입니다</h1>
              <p>작가입니다</p>
              <span>장르</span>
              <div>
                소개말입니다
              </div>
            </div>
          </div>
          <div tw="w-full flex flex-col py-4">
            <div tw="text-xl font-bold mb-4">
              회차 목록
            </div>
            <div tw="flex flex-col gap-4 mb-4">
              <div tw="flex justify-between items-center w-full border rounded px-4 py-2 shadow hover:(border-l-4 border-l-amber-400) duration-200">
                <div tw="">
                  <Link href="/storyroom/chapters/chapterList" tw="w-full block text-lg">제목입니다</Link>
                </div>
                <div tw="relative flex items-center">
                  <button tw="p-3 rounded-full hover:bg-gray-100" onClick={() => router.push("/storyroom/chapters/createChapter")}>
                    <HiOutlineEye tw="w-6 h-6 stroke-gray-400 hover:stroke-sky-400"/>
                  </button>
                  <button tw="p-3 rounded-full hover:bg-gray-100" onClick={() => router.push("/storyroom/chapters/createChapter")}>
                    <HiOutlinePencilSquare tw="w-6 h-6 stroke-gray-400 hover:stroke-green-400"/>
                  </button>
                  <button tw="p-3 rounded-full hover:bg-gray-100" onClick={() => router.push("/")}>
                    <HiOutlineTrash tw="w-6 h-6 stroke-gray-400 hover:stroke-red-400"/>
                  </button>
                </div>
              </div>
              <div tw="flex justify-between items-center w-full border rounded px-4 py-2 shadow hover:(border-l-4 border-l-amber-400) duration-200">
                <div tw="">
                  <Link href="/storyroom/chapters/chapterList" tw="w-full block text-lg">제목입니다</Link>
                </div>
                <div tw="relative flex items-center">
                  <button tw="p-3 rounded-full hover:bg-gray-100" onClick={() => router.push("/storyroom/chapters/createChapter")}>
                    <HiOutlineEye tw="w-6 h-6 stroke-gray-400 hover:stroke-sky-400"/>
                  </button>
                  <button tw="p-3 rounded-full hover:bg-gray-100" onClick={() => router.push("/storyroom/chapters/createChapter")}>
                    <HiOutlinePencilSquare tw="w-6 h-6 stroke-gray-400 hover:stroke-green-400"/>
                  </button>
                  <button tw="p-3 rounded-full hover:bg-gray-100" onClick={() => router.push("/")}>
                    <HiOutlineTrash tw="w-6 h-6 stroke-gray-400 hover:stroke-red-400"/>
                  </button>
                </div>
              </div>
              <div tw="flex justify-between items-center w-full border rounded px-4 py-2 shadow hover:(border-l-4 border-l-amber-400) duration-200">
                <div tw="">
                  <Link href="/storyroom/chapters/chapterList" tw="w-full block text-lg">제목입니다</Link>
                </div>
                <div tw="relative flex items-center">
                  <button tw="p-3 rounded-full hover:bg-gray-100" onClick={() => router.push("/storyroom/chapters/createChapter")}>
                    <HiOutlineEye tw="w-6 h-6 stroke-gray-400 hover:stroke-sky-400"/>
                  </button>
                  <button tw="p-3 rounded-full hover:bg-gray-100" onClick={() => router.push("/storyroom/chapters/createChapter")}>
                    <HiOutlinePencilSquare tw="w-6 h-6 stroke-gray-400 hover:stroke-green-400"/>
                  </button>
                  <button tw="p-3 rounded-full hover:bg-gray-100" onClick={() => router.push("/")}>
                    <HiOutlineTrash tw="w-6 h-6 stroke-gray-400 hover:stroke-red-400"/>
                  </button>
                </div>
              </div>
              <div tw="flex justify-between items-center w-full border rounded px-4 py-2 shadow hover:(border-l-4 border-l-amber-400) duration-200">
                <div tw="">
                  <Link href="/storyroom/chapters/chapterList" tw="w-full block text-lg">제목입니다</Link>
                </div>
                <div tw="relative flex items-center">
                  <button tw="p-3 rounded-full hover:bg-gray-100" onClick={() => router.push("/storyroom/chapters/createChapter")}>
                    <HiOutlineEye tw="w-6 h-6 stroke-gray-400 hover:stroke-sky-400"/>
                  </button>
                  <button tw="p-3 rounded-full hover:bg-gray-100" onClick={() => router.push("/storyroom/chapters/createChapter")}>
                    <HiOutlinePencilSquare tw="w-6 h-6 stroke-gray-400 hover:stroke-green-400"/>
                  </button>
                  <button tw="p-3 rounded-full hover:bg-gray-100" onClick={() => router.push("/")}>
                    <HiOutlineTrash tw="w-6 h-6 stroke-gray-400 hover:stroke-red-400"/>
                  </button>
                </div>
              </div>
              <div tw="flex justify-between items-center w-full border rounded px-4 py-2 shadow hover:(border-l-4 border-l-amber-400) duration-200">
                <div tw="">
                  <Link href="/storyroom/chapters/chapterList" tw="w-full block text-lg">제목입니다</Link>
                </div>
                <div tw="relative flex items-center">
                  <button tw="p-3 rounded-full hover:bg-gray-100" onClick={() => router.push("/storyroom/chapters/createChapter")}>
                    <HiOutlineEye tw="w-6 h-6 stroke-gray-400 hover:stroke-sky-400"/>
                  </button>
                  <button tw="p-3 rounded-full hover:bg-gray-100" onClick={() => router.push("/storyroom/chapters/createChapter")}>
                    <HiOutlinePencilSquare tw="w-6 h-6 stroke-gray-400 hover:stroke-green-400"/>
                  </button>
                  <button tw="p-3 rounded-full hover:bg-gray-100" onClick={() => router.push("/")}>
                    <HiOutlineTrash tw="w-6 h-6 stroke-gray-400 hover:stroke-red-400"/>
                  </button>
                </div>
              </div>
              <div tw="flex justify-between items-center w-full border rounded px-4 py-2 shadow hover:(border-l-4 border-l-amber-400) duration-200">
                <div tw="">
                  <Link href="/storyroom/chapters/chapterList" tw="w-full block text-lg">제목입니다</Link>
                </div>
                <div tw="relative flex items-center">
                  <button tw="p-3 rounded-full hover:bg-gray-100" onClick={() => router.push("/storyroom/chapters/createChapter")}>
                    <HiOutlineEye tw="w-6 h-6 stroke-gray-400 hover:stroke-sky-400"/>
                  </button>
                  <button tw="p-3 rounded-full hover:bg-gray-100" onClick={() => router.push("/storyroom/chapters/createChapter")}>
                    <HiOutlinePencilSquare tw="w-6 h-6 stroke-gray-400 hover:stroke-green-400"/>
                  </button>
                  <button tw="p-3 rounded-full hover:bg-gray-100" onClick={() => router.push("/")}>
                    <HiOutlineTrash tw="w-6 h-6 stroke-gray-400 hover:stroke-red-400"/>
                  </button>
                </div>
              </div>
              <div tw="flex justify-between items-center w-full border rounded px-4 py-2 shadow hover:(border-l-4 border-l-amber-400) duration-200">
                <div tw="">
                  <Link href="/storyroom/chapters/chapterList" tw="w-full block text-lg">제목입니다</Link>
                </div>
                <div tw="relative flex items-center">
                  <button tw="p-3 rounded-full hover:bg-gray-100" onClick={() => router.push("/storyroom/chapters/createChapter")}>
                    <HiOutlineEye tw="w-6 h-6 stroke-gray-400 hover:stroke-sky-400"/>
                  </button>
                  <button tw="p-3 rounded-full hover:bg-gray-100" onClick={() => router.push("/storyroom/chapters/createChapter")}>
                    <HiOutlinePencilSquare tw="w-6 h-6 stroke-gray-400 hover:stroke-green-400"/>
                  </button>
                  <button tw="p-3 rounded-full hover:bg-gray-100" onClick={() => router.push("/")}>
                    <HiOutlineTrash tw="w-6 h-6 stroke-gray-400 hover:stroke-red-400"/>
                  </button>
                </div>
              </div>
              <div tw="flex justify-between items-center w-full border rounded px-4 py-2 shadow hover:(border-l-4 border-l-amber-400) duration-200">
                <div tw="">
                  <Link href="/storyroom/chapters/chapterList" tw="w-full block text-lg">제목입니다</Link>
                </div>
                <div tw="relative flex items-center">
                  <button tw="p-3 rounded-full hover:bg-gray-100" onClick={() => router.push("/storyroom/chapters/createChapter")}>
                    <HiOutlineEye tw="w-6 h-6 stroke-gray-400 hover:stroke-sky-400"/>
                  </button>
                  <button tw="p-3 rounded-full hover:bg-gray-100" onClick={() => router.push("/storyroom/chapters/createChapter")}>
                    <HiOutlinePencilSquare tw="w-6 h-6 stroke-gray-400 hover:stroke-green-400"/>
                  </button>
                  <button tw="p-3 rounded-full hover:bg-gray-100" onClick={() => router.push("/")}>
                    <HiOutlineTrash tw="w-6 h-6 stroke-gray-400 hover:stroke-red-400"/>
                  </button>
                </div>
              </div>
              <div tw="flex justify-between items-center w-full border rounded px-4 py-2 shadow hover:(border-l-4 border-l-amber-400) duration-200">
                <div tw="">
                  <Link href="/storyroom/chapters/chapterList" tw="w-full block text-lg">제목입니다</Link>
                </div>
                <div tw="relative flex items-center">
                  <button tw="p-3 rounded-full hover:bg-gray-100" onClick={() => router.push("/storyroom/chapters/createChapter")}>
                    <HiOutlineEye tw="w-6 h-6 stroke-gray-400 hover:stroke-sky-400"/>
                  </button>
                  <button tw="p-3 rounded-full hover:bg-gray-100" onClick={() => router.push("/storyroom/chapters/createChapter")}>
                    <HiOutlinePencilSquare tw="w-6 h-6 stroke-gray-400 hover:stroke-green-400"/>
                  </button>
                  <button tw="p-3 rounded-full hover:bg-gray-100" onClick={() => router.push("/")}>
                    <HiOutlineTrash tw="w-6 h-6 stroke-gray-400 hover:stroke-red-400"/>
                  </button>
                </div>
              </div>
              <div tw="flex justify-between items-center w-full border rounded px-4 py-2 shadow hover:(border-l-4 border-l-amber-400) duration-200">
                <div tw="">
                  <Link href="/storyroom/chapters/chapterList" tw="w-full block text-lg">제목입니다</Link>
                </div>
                <div tw="relative flex items-center">
                  <button tw="p-3 rounded-full hover:bg-gray-100" onClick={() => router.push("/storyroom/chapters/createChapter")}>
                    <HiOutlineEye tw="w-6 h-6 stroke-gray-400 hover:stroke-sky-400"/>
                  </button>
                  <button tw="p-3 rounded-full hover:bg-gray-100" onClick={() => router.push("/storyroom/chapters/createChapter")}>
                    <HiOutlinePencilSquare tw="w-6 h-6 stroke-gray-400 hover:stroke-green-400"/>
                  </button>
                  <button tw="p-3 rounded-full hover:bg-gray-100" onClick={() => router.push("/")}>
                    <HiOutlineTrash tw="w-6 h-6 stroke-gray-400 hover:stroke-red-400"/>
                  </button>
                </div>
              </div>
              
              

            </div>
            <div tw="w-full flex justify-center gap-6">
              <a tw="block border px-2.5 py-2 rounded"><HiOutlineChevronLeft tw="w-6 h-6"/></a>
              <a tw="block bg-black text-white border px-4 py-2 rounded">1</a>
              <a tw="block border px-4 py-2 rounded hover:bg-gray-400">2</a>
              <a tw="block border px-4 py-2 rounded">3</a>
              <a tw="block border px-4 py-2 rounded">4</a>
              <a tw="block border px-4 py-2 rounded">5</a>
              <a tw="block border px-2.5 py-2 rounded"><HiOutlineChevronRight tw="w-6 h-6"/></a>
            </div>
          </div>
        </div>
      </main>
      <footer>
        
      </footer>
    </>
  )
}

export default ChapterList;