import Head from "next/head"
import tw from 'twin.macro'
import {faker} from '@faker-js/faker/locale/ko'
import Image from "next/image"
import { HiOutlineArrowLeft, HiOutlineChevronLeft, HiOutlineChevronRight, HiOutlineEye, HiOutlinePencilSquare, HiOutlineTrash } from 'react-icons/hi2'
import Link from "next/link"
import { router } from "next/router"
import { useEffect, useState } from "react"
import Pagination from "../../../components/overlay/pagination/Pagination"
import ChapterItem from "./chapterItem"
import Button from "../../../components/core/button/Button"

const ChapterList = () => {

  const imgUrl = faker.image.animals(300,400);

  const chapter = {
    title: faker.lorem.lines(1)
  }

  const [data, setData] = useState([]);
  const [limit, setLimit] = useState(10);
  const [page, setPage] = useState(1);
  const offset = (page - 1) * limit;

  useEffect(() => {
    setData(Array(227).fill(chapter))
  },[])

  return (
    <>
      <Head>
        <title>쿠키블</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header tw="w-full border-b border-gray-200">
        <nav tw="flex justify-start items-center max-w-screen-lg mx-auto py-2">
          <div tw="relative">
            <button tw="p-3">
              <HiOutlineArrowLeft tw="w-6 h-6 stroke-gray-400" />
            </button>
          </div>
          <div tw="flex items-center text-xl font-bold">회차 목록</div>
        </nav>
      </header>
      <nav tw="max-w-screen-lg mx-auto my-4">
        <div tw="flex justify-between divide-x border rounded-lg border-gray-200 mx-4">
          <Link tw="w-1/3 text-center py-3 hover:bg-gray-100" href="/storyroom/chapters">회차 목록</Link>
          <Link tw="w-1/3 text-center py-3 hover:bg-gray-100" href="/storyroom/chapters/notice">공지 목록</Link>
          <Link tw="w-1/3 text-center py-3 hover:bg-gray-100" href="/storyroom/analysis/daily">일별 통계</Link>
        </div> 
      </nav>
      <main tw="max-w-screen-lg mx-auto">
        <div tw="flex lg:flex-row flex-col gap-12 px-4">
          <div tw="flex flex-col border rounded px-4 py-3 my-3">
            <div tw="flex justify-center items-center rounded-lg overflow-hidden mb-4">
              <Image src={imgUrl} alt="random test image" width={300} height={400}/>
            </div>
            <div tw="flex flex-col">
              <h1 tw="text-2xl">제목입니다</h1>
              <p>작가입니다</p>
              <span>장르</span>
              <div>
                소개말입니다
              </div>
            </div>
          </div>
          <div tw="w-full flex flex-col py-4">
            <div tw="flex items-center justify-between text-xl font-bold mb-4">
              <h3>회차 목록</h3>
              <Button variant="solid" leftIcon={<HiOutlinePencilSquare tw="w-6 h-6 text-white"/>} label="회차 쓰기" size="lg" />
            </div>
            <div tw="flex flex-col gap-4 mb-4">
            {data.slice(offset, offset + limit).map((data, i) => (
              <ChapterItem key={i} id={i+1} chapter={data}/>
            ))}
            </div>
            <div tw="flex justify-center">
              <Pagination total={data.length} limit={limit} page={page} setPage={setPage}/>
            </div>
          </div>
        </div>
      </main>
      <footer>
        
      </footer>
    </>
  )
}

export default ChapterList;