import Head from 'next/head'
import Image from 'next/image'
import tw from 'twin.macro'
import { Swiper, SwiperSlide } from 'swiper/react'
import 'swiper/swiper.min.css'
import 'swiper/css/navigation'
import 'swiper/css/pagination'
import { Pagination, Navigation, Scrollbar, Autoplay } from "swiper"
import { HiBars3, HiMagnifyingGlass, HiOutlineBell, HiChevronRight, HiChevronLeft } from 'react-icons/hi2'
import Button from '../components/core/button/Button'
import Avatar from '../components/core/avatar/Avatar'
import MainCarousel from '../components/overlay/mainCarosel/MainCarosel'
import { useEffect, useRef, useState } from 'react'

export default function Home() {

  const handleAvatar = async () => {
    const res = await fetch("https://i.pravatar.cc/48");

    return res.json();
  }

  const src= "https://i.pravatar.cc/48/"

  const [cardList, setCardList] = useState("");

  const [isLoading, setIsLoading] = useState(false); 
  const [isError, setIsError] = useState(false); 
 
  const [page, setPage] = useState(1);
  useEffect(() => {
    const fetchData = async () => {
      const url = `https://picsum.photos/v2/list`;
      const response = await fetch(url);
      if (!response.ok) throw new Error("Response Error");
      setCardList((response).json());
      console.log(cardList)
    };
    fetchData().catch((error) => console.log(error));
  }, []);

  const prevRef = useRef(null);
  const nextRef = useRef(null);

  return (
    <>
      <Head>
        <title>쿠키블</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header tw="p-2 border-b border-gray-200">
        <nav tw="flex justify-between items-center max-w-screen-lg mx-auto">
          <div tw="lg:hidden">
            <button
              type="button"
              tw="p-3 hover:bg-gray-50 active:bg-gray-100 rounded-full"
            >
              <HiBars3 tw="w-6 h-6 text-gray-400"/>
            </button>
          </div>
          <div tw="flex justify-between space-x-4">
            <div tw="hidden lg:inline-flex">
              <span tw="text-3xl font-bold">C</span>
              <span tw="text-3xl font-bold text-[#E7CE96]">OO</span>
              <span tw="text-3xl font-bold">KVEL</span>
            </div>

            <div tw="hidden lg:flex space-x-4 text-lg">
              <a tw="px-4 py-2 hover:(font-bold bg-gray-50) active:bg-gray-100 rounded-lg" href="">자유연재</a>
              <a tw="px-4 py-2 hover:font-bold active:bg-gray-100 rounded-lg" href="">자유연재</a>
              <a tw="px-4 py-2 hover:font-bold active:bg-gray-100 rounded-lg" href="">자유연재</a>
              <a tw="px-4 py-2 hover:font-bold active:bg-gray-100 rounded-lg" href="">자유연재</a>
            </div>
          </div>

          <div tw="flex justify-between items-center">
            <div tw="">
              <button
                type="button"
                tw="p-3 hover:bg-gray-50 active:bg-gray-100 rounded-full"
              >
                <HiMagnifyingGlass tw="w-6 h-6 text-gray-400"/>
              </button>
            </div>
            <div tw="hidden">

            </div>
            <div tw="flex justify-between items-center space-x-2">
              <button
               type="button"
               tw="hidden lg:block p-3 hover:bg-gray-50 active:bg-gray-100 rounded-full"
              >
                <HiOutlineBell tw="w-6 h-6 text-gray-400"/>
              </button>
              {/* <Avatar size="sm" alt="avatar" src={"https://i.pravatar.cc/48"} width={48} height={48}/> */}
            </div>
          </div>
        </nav>
      </header>
      <main tw="flex flex-col">
        <section tw="relative w-full h-80">
          <div tw="lg:max-w-[1970px] w-full relative mx-auto p-0 flex justify-center">
          <Swiper
            tw="min-w-[calc((3*480px) + (3* 20px))] lg:min-w-[calc((3*560px) + (3* 20px))] lg:max-w-[calc((3*560px) + (3* 20px))] w-full flex flex-col items-center"
            modules={[Pagination, Navigation, Autoplay]}
            loop={true}
            centeredSlides={true}
            loopAdditionalSlides={1}
            spaceBetween={10}
            slidesPerView={3}
            watchOverflow={true}
            navigation={{prevEl: prevRef.current, nextEl: nextRef.current}}
            pagination={{ clickable: true, type: 'bullets' }}
            scrollbar={{ draggable: true, el: null }}
            autoplay={true}
            
            onBeforeInit={(swiper) => {
              swiper.params.navigation.prevEl = prevRef.current;
              swiper.params.navigation.nextEl = nextRef.current;
              swiper.navigation.update();
            }}
            breakpoints={{
              576: {
                slidesPerView: 1,
                spaceBetween: 10
              },
              768: {
                slidesPerView: 2,
                spaceBetween: 10
              },
              992: {
                slidesPerView: 3,
                spaceBetween: 10
              },
              1200: {
                slidesPerView: 3,
                spaceBetween: 10
              }
            }}
          >
            <SwiperSlide><div tw="w-[580px] md:min-w-[500px] md:px-2.5">
              <div tw="min-w-[500px] w-[580px] rounded-lg overflow-hidden">
                <div tw="w-full relative aspect-w-4 aspect-h-3 pb-[75%] text-white">
                  <img tw="absolute object-center object-cover w-full top-0 left-0" src="https://picsum.photos/200/300?random=1" alt="1"/>
                  <div tw=""></div>
                </div>
              </div></div>
            </SwiperSlide>
            <SwiperSlide><div tw="w-[580px] md:min-w-[500px] md:px-2.5">
              <div tw="min-w-[500px] w-[580px] rounded-lg overflow-hidden">
                <div tw="w-full relative aspect-w-4 aspect-h-3 pb-[75%] text-white">
                  <img tw="absolute object-center object-cover w-full top-0 left-0" src="https://picsum.photos/200/300?random=2" alt="2"/>
                  <div tw=""></div>
                </div>
              </div></div>
            </SwiperSlide>
            <SwiperSlide><div tw="w-[580px] md:min-w-[500px] md:px-2.5">
              <div tw="min-w-[500px] w-[580px] rounded-lg overflow-hidden">
                <div tw="w-full relative aspect-w-4 aspect-h-3 pb-[75%] text-white">
                  <img tw="absolute object-center object-cover w-full top-0 left-0" src="https://picsum.photos/200/300?random=3" alt="1"/>
                  <div tw=""></div>
                </div>
              </div></div>
            </SwiperSlide>
            <SwiperSlide><div tw="w-[580px] md:min-w-[500px] md:px-2.5">
              <div tw="min-w-[500px] w-[580px] rounded-lg overflow-hidden">
                <div tw="w-full relative aspect-w-4 aspect-h-3 pb-[75%] text-white">
                  <img tw="absolute object-center object-cover w-full top-0 left-0" src="https://picsum.photos/200/300?random=4" alt="1"/>
                  <div tw=""></div>
                </div>
              </div></div>
            </SwiperSlide>
            <SwiperSlide><div tw="w-[580px] md:min-w-[500px] md:px-2.5">
              <div tw="min-w-[500px] w-[580px] rounded-lg overflow-hidden">
                <div tw="w-full relative aspect-w-4 aspect-h-3 pb-[75%] text-white">
                  <img tw="absolute object-center object-cover w-full top-0 left-0" src="https://picsum.photos/200/300?random=5" alt="1"/>
                  <div tw=""></div>
                </div>
              </div></div>
            </SwiperSlide>
            <SwiperSlide><div tw="w-[580px] md:min-w-[500px] md:px-2.5">
              <div tw="min-w-[500px] w-[580px] rounded-lg overflow-hidden">
                <div tw="w-full relative aspect-w-4 aspect-h-3 pb-[75%] text-white">
                  <img tw="absolute object-center object-cover w-full top-0 left-0" src="https://picsum.photos/200/300?random=6" alt="1"/>
                  <div tw=""></div>
                </div>
              </div></div>
            </SwiperSlide>
            <SwiperSlide><div tw="w-[580px] md:min-w-[500px] md:px-2.5">
              <div tw="min-w-[500px] w-[580px] rounded-lg overflow-hidden">
                <div tw="w-full relative aspect-w-4 aspect-h-3 pb-[75%] text-white">
                  <img tw="absolute object-center object-cover w-full top-0 left-0" src="https://picsum.photos/200/300?random=7" alt="1"/>
                  <div tw=""></div>
                </div>
              </div></div>
            </SwiperSlide>
            <SwiperSlide>
              <div tw="w-[580px] md:min-w-[500px] md:px-2.5">
              <div tw="min-w-[500px] w-[580px] rounded-lg overflow-hidden">
                <div tw="w-full relative aspect-w-4 aspect-h-3 pb-[75%] text-white">
                  <img tw="absolute object-center object-cover w-full top-0 left-0" src="https://picsum.photos/200/300?random=8" alt="1"/>
                  <div tw=""></div>
                </div>
              </div>
              </div>
            </SwiperSlide>
            <SwiperSlide>
              <div tw="w-[580px] md:min-w-[500px] md:px-2.5">
              <div tw="min-w-[500px] w-[580px] rounded-lg overflow-hidden">
                <div tw="w-full relative aspect-w-4 aspect-h-3 pb-[75%] text-white">
                  <img tw="absolute object-center object-cover w-full top-0 left-0" src="https://picsum.photos/200/300?random=9" alt="1"/>
                  <div tw=""></div>
                </div>
              </div>
              </div>
            </SwiperSlide>
          </Swiper>
          <div tw="absolute w-full flex justify-between items-center top-1/3 z-20">
            <button
              ref={prevRef}
              type="button"
              tw="min-w-fit h-full p-3 hover:bg-gray-50 text-gray-400 lg:hover:bg-transparent lg:hover:text-sky-500 rounded-full lg:rounded-none"
            >
              <HiChevronLeft tw="w-12 h-12 text-gray-400 hover:lg:text-sky-500"/>
            </button>
            <button
              ref={nextRef}
              type="button"
              tw="min-w-fit h-full p-3 hover:bg-gray-50 text-gray-400 lg:hover:bg-transparent lg:hover:text-sky-500 rounded-full lg:rounded-none"
            >
              <HiChevronRight tw="w-12 h-12"/>
            </button>
          </div>
          </div>         
        </section>      
        <section tw="max-w-screen-lg mx-auto mt-52">
          <div tw="w-full flex">
            <div tw="w-[500px] flex justify-between items-center border-b border-gray-200 px-4 py-2">
              <h2 tw="text-xl font-bold">인기 콘텐츠</h2>
              <HiChevronRight tw="w-6 h-6" />
            </div>
          </div>
        </section>
        <section tw="max-w-screen-lg mx-auto h-screen">
          <div tw="w-full flex">
            <div tw="w-[500px] flex justify-between items-center border-b border-gray-200 px-4 py-2">
              <h2 tw="text-xl font-bold">인기 콘텐츠</h2>
              <HiChevronRight tw="w-6 h-6" />
            </div>
          </div>
        </section>
      </main>
      <footer>
        
      </footer>
    </>
  )
}

