import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import tw from 'twin.macro'
import { Swiper, SwiperSlide } from 'swiper/react'
import 'swiper/css'
import 'swiper/css/navigation'
import 'swiper/css/pagination'
import { Pagination, Navigation, Scrollbar, Autoplay } from "swiper"
import { HiBars3, HiMagnifyingGlass, HiOutlineBell, HiChevronRight, HiChevronLeft, HiXMark, HiPhoto } from 'react-icons/hi2'
import Button from '../components/core/button/Button'
import Avatar from '../components/core/avatar/Avatar'
import MainCarousel from '../components/overlay/mainCarosel/MainCarosel'
import { useEffect, useRef, useState } from 'react'
import useDetectClose from '../components/hooks/useDetectClose'
import Toggle from '../components/forms/toggle/Toggle'

export default function Usepage() {

  const prevRef = useRef(null);
  const nextRef = useRef(null);
  const pageRef= useRef(null);

  const [enabled, setEnabled] = useState(false);
  const [toggle, setToggle] = useState(false);

  const [myPageIsOpen, myPageRef, myPageHandler] = useDetectClose(false);
  const [sidebarIsOpen, sidebarRef, sidebarHandler] = useDetectClose(false);
  return (
    <>
      <Head>
        <title>쿠키블 : 스토리룸</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header tw="min-w-[425px] border-b border-gray-200">
        <nav tw="relative flex justify-between items-center max-w-screen-lg mx-auto px-4 py-2">         
          <div tw="flex justify-between items-center">
            <a tw="inline-flex mb-1" href="">           
              <span tw="text-2xl font-bold">O</span>
              <span tw="text-2xl font-bold text-[#E7CE96]">V</span>
              <span tw="text-2xl font-bold">EN</span>
            </a>
          </div>
          <div tw="flex space-x-4 text-base">
            <a tw="px-4 py-2 font-semibold" href="">작품 등록</a>
          </div>
          <div tw="flex justify-between items-center">            
            <button
               type="button"
               tw="hidden lg:block p-3 hover:bg-gray-50 active:bg-gray-100 rounded-full"
              >
              <HiOutlineBell tw="w-6 h-6 text-gray-400"/>
            </button>
            <div tw="hidden">

            </div>              
              {
                 
              <>
              <button tw="hidden md:block ml-3" type="button" ref={myPageRef} onClick={myPageHandler}>
                  <Avatar size="sm" alt="avatar" src={"https://api.lorem.space/image/face?w=128&h=128&hash=BDC01094"} width={32} height={32}/>
              </button>
              <div css={[tw`hidden absolute bg-white w-[100px] h-full rounded-lg top-10 right-0 z-10 mt-4 origin-top-right shadow duration-150 ease-in-out`, myPageIsOpen ? tw`opacity-100`: tw`opacity-0`]}>
                <ul tw="text-center">
                  <li>메뉴</li>
                  <li>메뉴</li>
                </ul>
              </div>
              </>
              }
            <div tw="lg:hidden">
            <button
              ref={sidebarRef}
              type="button"
              tw="p-3 hover:bg-gray-50 active:bg-gray-100 rounded-full"
              onClick={sidebarHandler}
            >
              <HiBars3 tw="w-6 h-6 text-gray-400"/>
            </button>
            </div>
          </div>
        </nav>
      </header>  
      <aside tw="absolute w-[300px] md:hidden h-screen bg-gray-50 top-0 right-0 z-50 duration-300 transition-all ease-in-out shadow" css={[sidebarIsOpen ? tw`translate-x-0`: tw`translate-x-[300px]`]}>
        <nav tw="">
          <div tw="flex justify-end border-b border-gray-400 p-3">
            <button type="button" onClick={sidebarHandler}><HiXMark tw="w-8 h-8"/></button>
          </div>
          <div tw="flex items-center p-3">
            <Avatar size="md" alt="avatar" src={"https://api.lorem.space/image/face?w=128&h=128&hash=BDC01094"} width={48} height={48}/>
            <div tw="ml-4">
              <p tw="text-xl font-bold">빵냥 님</p>
              <span tw="text-gray-400">mkht0210@gmail.com</span>
            </div>
          </div>
          <div tw="flex flex-col p-3">
            <a tw="px-4 py-2 w-full hover:bg-gray-100 font-semibold text-lg">대시보드</a>
            <a tw="px-4 py-2 w-full hover:bg-gray-100 font-semibold text-lg">작품 목록</a>
            <a tw="px-4 py-2 w-full hover:bg-gray-100 font-semibold text-lg">작품 쓰기</a>
            <a tw="px-4 py-2 w-full hover:bg-gray-100 font-semibold text-lg">스토리룸</a>
            <a tw="px-4 py-2 w-full hover:bg-gray-100 font-semibold text-lg">통계</a>
            <a tw="px-4 py-2 w-full hover:bg-gray-100 font-semibold text-lg">설정</a>
            <a tw="px-4 py-2 w-full hover:bg-gray-100 font-semibold text-lg">고객센터</a>           
          </div>
        </nav>
      </aside>
      <main tw="flex flex-col mt-12 overflow-x-hidden">    
        <section tw="container mx-auto mt-12">
          <div tw="max-w-screen-lg mx-auto px-2">
            <div tw="w-full border-b border-gray-200 mb-4"/>

            <div tw="w-full flex flex-col md:flex-row py-6 justify-center md:justify-between items-center px-4">
              <div tw="">
                <div tw="">
                  <div tw="block relative mb-4">
                    <label htmlFor="uploadImage" tw="block relative bg-gray-100 flex flex-col items-center justify-center w-32 h-40 rounded-lg overflow-hidden py-2 px-4 hover:bg-gray-200 active:bg-gray-300">
                      <HiPhoto tw="w-8 h-8 fill-gray-400"/>
                      <span tw="block text-sm text-gray-400 select-none">이미지 업로드</span>
                      <input id="uploadImage" tw="hidden" type="file"/>
                    </label>                   
                  </div>
                </div>
                <div tw="flex flex-col gap-6 items-stretch">
                  <form>
                    <div tw="mb-4">
                      <label tw="mr-2" htmlFor="title">제목</label>
                      <input id="title" tw="px-4 py-2 border border-gray-300 focus:(ring-2 border-sky-400 ring-sky-400) rounded-lg" type="text"/>
                    </div>
                    <div tw="mb-4">
                      <label tw="mr-2" htmlFor="description">설명</label>
                      <textarea id="description" tw="px-4 py-2 border border-gray-300 focus:(ring-2 border-sky-400 ring-sky-400) rounded-lg resize-none" type="text"/>
                    </div>
                    <div tw="mb-4">
                      <label tw="mr-2" htmlFor="length">작품 길이</label>
                      <input id="long" tw="border border-gray-400 text-sky-400 focus:(ring-2 border-sky-400 ring-sky-400)" name="length" type="radio"/>
                      <label tw="ml-2 mr-4" htmlFor="long">장편</label>
                      <input id="short" tw="border border-gray-400 text-sky-400 focus:(ring-2 border-sky-400 ring-sky-400)" name="length" type="radio"/>
                      <label tw="ml-2" htmlFor="short">단편</label>
                    </div>
                    <div tw="mb-4">
                      <label tw="mr-2" htmlFor="visible">공개유무</label>
                      <label htmlFor="toggle1" tw="md:w-14 md:h-7 w-12 h-6 flex items-center bg-gray-300 rounded-full p-1 cursor-pointer duration-300"
                      css={[enabled ? tw`bg-sky-600`: tw``]}
                      >
                      <input id="toggle1" tw="hidden" type="checkbox" checked={enabled} onChange={()=>{setEnabled(!enabled)}}/>
                      <div tw="bg-white md:w-6 md:h-6 h-5 w-5 rounded-full shadow-md transform duration-300"
                      css={[
                        enabled ? tw`transform translate-x-5 md:translate-x-6` : tw``
                      ]}
                      ></div>
                     </label>
                    </div>
                    <div tw="mb-4">
                      <label tw="mr-2">완결유무</label>
                      <label htmlFor="toggle" tw="md:w-14 md:h-7 w-12 h-6 flex items-center bg-gray-300 rounded-full p-1 cursor-pointer duration-300"
                      css={[enabled ? tw`bg-sky-600`: tw``]}
                      >
                      <input id="toggle" tw="hidden" type="checkbox" checked={enabled} onChange={()=>{setEnabled(!enabled)}}/>
                      <div tw="bg-white md:w-6 md:h-6 h-5 w-5 rounded-full shadow-md transform duration-300"
                      css={[
                        enabled ? tw`transform translate-x-5 md:translate-x-6` : tw``
                      ]}
                      ></div>
                     </label>
                    </div>
                    <div tw="mb-4">
                      <label tw="mr-2" htmlFor="give">후원가능유무</label>
                      <label htmlFor="toggle2" tw="md:w-14 md:h-7 w-12 h-6 flex items-center bg-gray-300 rounded-full p-1 cursor-pointer duration-300"
                      css={[toggle ? tw`bg-sky-600`: tw``]}
                      >
                      <input id="toggle2" tw="sr-only" type="checkbox" checked={toggle} onChange={()=>{setToggle(!toggle)}}/>
                      <div tw="bg-white md:w-6 md:h-6 h-5 w-5 rounded-full shadow-md transform duration-300"
                      css={[
                        toggle ? tw`transform translate-x-5 md:translate-x-6` : tw``
                      ]}
                      ></div>
                     </label>
                    </div>
                    <div tw="mb-4">
                      <label tw="mr-2" htmlFor="tags">태그</label>
                      <input id="tags" tw="px-4 py-2 border border-gray-300 focus:(ring-2 border-sky-400 ring-sky-400) rounded-lg" type="text"/>
                    </div>
                    <div tw="">
                    

                    </div>

                  </form>               
                </div>
              </div>
            </div>
          </div>
        </section>
        <section tw="max-w-screen-lg mx-auto">
                
        </section>
      </main>
      <footer>
        
      </footer>
    </>
  )
}

